git rm -f EcuabCanIf
git rm -f EcuabFee
git rm -f LibAutosar
git rm -f McalAdc
git rm -f McalCan
git rm -f McalDio
git rm -f McalFls
git rm -f McalGpt
git rm -f McalWdg
git rm -f ProjectCfg
git rm -f ProjectCompiler
git rm -f SwcServiceCanSm
git rm -f SwcServiceCanTp
git rm -f SwcServiceCom
git rm -f SwcServiceComM
git rm -f SwcServiceDcm
git rm -f SwcServiceDem
git rm -f SwcServiceDet
git rm -f SwcServiceEcuM
git rm -f SwcServiceNvM
git rm -f SwcServiceOs
git rm -f SwcServicePduR
git rm -f SwcServiceStartUp
git rm -f common

