MKLINK /D EcuabCanIf        ..\..\..\..\modules\EcuabCanIf\VirtualECU_R2023
MKLINK /D EcuabFee          ..\..\..\..\modules\EcuabFee\VirtualECU_R2023
MKLINK /D McalAdc           ..\..\..\..\modules\McalAdc\VirtualMachine_R2023
MKLINK /D McalCan           ..\..\..\..\modules\McalCan\VirtualMachine_R2023
MKLINK /D McalDio           ..\..\..\..\modules\McalDio\VirtualMachine_R2023
MKLINK /D McalFls           ..\..\..\..\modules\McalFls\VirtualMachine_R2023
MKLINK /D McalGpt           ..\..\..\..\modules\McalGpt\VirtualMachine_R2023
MKLINK /D McalWdg           ..\..\..\..\modules\McalWdg\VirtualMachine_R2023
MKLINK /D SwcServiceCanSm   ..\..\..\..\modules\SwcServiceCanSm\p_VirtualEcu_R2023
MKLINK /D SwcServiceCanTp   ..\..\..\..\modules\SwcServiceCanTp\p_VirtualEcu_R2023
MKLINK /D SwcServiceCom     ..\..\..\..\modules\SwcServiceCom\p_VirtualEcu_R2023
MKLINK /D SwcServiceComM    ..\..\..\..\modules\SwcServiceComM\p_VirtualEcu_R2023
MKLINK /D SwcServiceDcm     ..\..\..\..\modules\SwcServiceDcm\p_VirtualEcu_R2023
MKLINK /D SwcServiceDem     ..\..\..\..\modules\SwcServiceDem\p_VirtualEcu_R2023
MKLINK /D SwcServiceDet     ..\..\..\..\modules\SwcServiceDet\p_VirtualEcu_R2023
MKLINK /D SwcServiceEcuM    ..\..\..\..\modules\SwcServiceEcuM\p_VirtualEcu_R2023
MKLINK /D SwcServiceNvM     ..\..\..\..\modules\SwcServiceNvM\p_VirtualEcu_R2023
MKLINK /D SwcServiceOs      ..\..\..\..\modules\SwcServiceOs\p_VirtualEcu_R2023
MKLINK /D SwcServicePduR    ..\..\..\..\modules\SwcServicePduR\p_VirtualEcu_R2023
MKLINK /D SwcServiceStartUp ..\..\..\..\modules\SwcServiceStartUp\p_VirtualEcu_R2023
MKLINK /D common            ..\..\..\..\modules\common\p_VirtualEcu_R2023
MKLINK /D ProjectCfg        ..\..\..\..\modules\ProjectCfg\p_VirtualEcu_R2023
MKLINK /D ProjectCompiler   ..\..\..\..\modules\ProjectCompiler\CmsisGhs_R2023
