MKLINK /D EcuabCanIf        ..\..\..\..\repo_submodules\EcuabCanIf\VirtualECU_R2023
MKLINK /D EcuabFee          ..\..\..\..\repo_submodules\EcuabFee\VirtualECU_R2023
MKLINK /D LibAutosar        ..\..\..\..\repo_submodules\LibAutosar\p_VirtualEcu_R2023
MKLINK /D McalAdc           ..\..\..\..\repo_submodules\McalAdc\VirtualMachine_R2023
MKLINK /D McalCan           ..\..\..\..\repo_submodules\McalCan\VirtualMachine_R2023
MKLINK /D McalDio           ..\..\..\..\repo_submodules\McalDio\VirtualMachine_R2023
MKLINK /D McalFls           ..\..\..\..\repo_submodules\McalFls\VirtualMachine_R2023
MKLINK /D McalGpt           ..\..\..\..\repo_submodules\McalGpt\VirtualMachine_R2023
MKLINK /D McalWdg           ..\..\..\..\repo_submodules\McalWdg\VirtualMachine_R2023
MKLINK /D SwcServiceCanSm   ..\..\..\..\repo_submodules\SwcServiceCanSm\p_VirtualEcu_R2023
MKLINK /D SwcServiceCanTp   ..\..\..\..\repo_submodules\SwcServiceCanTp\p_VirtualEcu_R2023
MKLINK /D SwcServiceCom     ..\..\..\..\repo_submodules\SwcServiceCom\p_VirtualEcu_R2023
MKLINK /D SwcServiceComM    ..\..\..\..\repo_submodules\SwcServiceComM\p_VirtualEcu_R2023
MKLINK /D SwcServiceDcm     ..\..\..\..\repo_submodules\SwcServiceDcm\p_VirtualEcu_R2023
MKLINK /D SwcServiceDem     ..\..\..\..\repo_submodules\SwcServiceDem\p_VirtualEcu_R2023
MKLINK /D SwcServiceDet     ..\..\..\..\repo_submodules\SwcServiceDet\p_VirtualEcu_R2023
MKLINK /D SwcServiceEcuM    ..\..\..\..\repo_submodules\SwcServiceEcuM\p_VirtualEcu_R2023
MKLINK /D SwcServiceNvM     ..\..\..\..\repo_submodules\SwcServiceNvM\p_VirtualEcu_R2023
MKLINK /D SwcServiceOs      ..\..\..\..\repo_submodules\SwcServiceOs\p_VirtualEcu_R2023
MKLINK /D SwcServicePduR    ..\..\..\..\repo_submodules\SwcServicePduR\p_VirtualEcu_R2023
MKLINK /D SwcServiceStartUp ..\..\..\..\repo_submodules\SwcServiceStartUp\p_VirtualEcu_R2023
MKLINK /D common            ..\..\..\..\repo_submodules\common\p_VirtualEcu_R2023
MKLINK /D ProjectCfg        ..\..\..\..\repo_submodules\ProjectCfg\p_VirtualEcu_R2023
MKLINK /D ProjectCompiler   ..\..\..\..\repo_submodules\ProjectCompiler\CmsisGhs_R2023
